### ISSUE TITLE
Open-Source Sapphire

### ISSUE THREAD

**Issue by Kriechi** [Sapphire-CM/Sapphire#336]
I want to open-source Sapphire. We already have it MIT-licensed, so we are good to go.
We should create a GitHub organisation and put all Sapphire-related code there.
- [ ] Sapphire Rails app
- [ ] Sapphire NNTP
- [ ] backup scripts
- [ ] Apache config & start script (optional, only if not security relevant)
- [ ] Postgres config & start script (optional, only if not security relevant)
- [ ] Redis config & start script (optional, only if not security relevant)
- [ ] Sidekiq config & start script (optional, only if not security relevant)

Before we do that, we should make sure the repository does not contain private information (server names, passwords, usernames, email addresses, etc). 
- [ ] Maybe we should rewrite history a little bit (or completely?).
- [ ] Should we move the issue tracker - or start from a clean slate?

**Comment by matthee** [comment]
Finally done!
